# Copyright (c) 2015-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD+Patents license found in the
# LICENSE file in the root directory of this source tree.

-include makefile.inc

SRC=$(wildcard *.cpp)
OBJ=$(SRC:.cpp=.o)


############################
# Building

all: libfaiss.a libfaiss.$(SHAREDEXT)

libfaiss.a: $(OBJ)
	ar r $@ $^

libfaiss.$(SHAREDEXT): $(OBJ)
	$(CXX) $(LDFLAGS) $(SHAREDFLAGS) -o $@ $^ $(LIBS)

%.o: %.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(CPUFLAGS) -c $< -o $@

clean:
	rm -f libfaiss.*
	rm -f $(OBJ)


############################
# Installing

install: libfaiss.a libfaiss.$(SHAREDEXT) installdirs
	cp libfaiss.a libfaiss.$(SHAREDEXT) $(DESTDIR)@libdir@
	cp *.h $(DESTDIR)@includedir@/faiss/

installdirs:
	$(MKDIR_P) $(DESTDIR)@libdir@ $(DESTDIR)@includedir@/faiss

uninstall:
	rm $(DESTDIR)@libdir@/libfaiss.a
	rm $(DESTDIR)@libdir@/libfaiss.$(SHAREDEXT)
	rm -rf $(DESTDIR)@includedir@/faiss


#############################
# Dependencies

-include makefile.dep

# The above makefile.dep is generated by the following target:
dep:
	for i in $(SRC); do \
		cpp $(CXXFLAGS) -MM $$i; \
	done > makefile.dep


#############################
# Tests

test: libfaiss.a
	make -C tests


#############################
# Demos

demos: libfaiss.a
	make -C demos


#############################
# Python

py: python/_swigfaiss.so

python/_swigfaiss.so: libfaiss.a
	$(MAKE) -C python _swigfaiss.so


.SUFFIXES: .cpp .o
.PHONY: all clean dep install installdirs py test uninstall
