package:
  name: faiss
  version: "1.5.0"

source:
  git_rev: packages
  git_url: https://github.com/beauby/faiss.git

requirements:
  build:
    - python {{ python }}
    - intel-openmp # [osx]
    - gcc
    - mkl
    - numpy
    - setuptools
    - blas=*=mkl

  run:
    - python {{ python }}
    - intel-openmp # [osx]
    - gcc
    - mkl
    - numpy

test:
  imports:
    - faiss
  source_files: tests
  commands:
    - python -m unittest discover tests/ -v

about:
  home: https://github.com/facebookresearch/faiss
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A library for efficient similarity search and clustering of dense vectors.
