package:
  name: faiss
  version: "1.3.0"

source:
  git_rev: v1.3.0
  git_url: https://github.com/facebookresearch/faiss.git

requirements:
  host:
    - python {{ python }}
    - system # [linux]
    - intel-openmp # [osx]
    - gcc
    - mkl
    - numpy
    - setuptools

  run:
    - python {{ python }}
    - system # [linux]
    - intel-openmp # [osx]
    - gcc
    - mkl
    - numpy
    - cudatoolkit

test:
  imports:
    - faiss
  source_files: tests
  commands:
    - python -m unittest discover tests/ -v

about:
  home: https://github.com/facebookresearch/faiss
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A library for efficient similarity search and clustering of dense vectors.
