# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

{% set version = environ.get('GIT_DESCRIBE_TAG') %}
{% set number = environ.get('GIT_DESCRIBE_NUMBER') %}
{% set target = "cuda" ~ cudatoolkit if cudatoolkit != "None" else "cpu" %}

package:
  name: faiss-pkg
  version: {{ version }}

build:
  number: {{ number }}

about:
  home: https://github.com/facebookresearch/faiss
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A library for efficient similarity search and clustering of dense vectors.

source:
  git_url: ../../

outputs:
  - name: libfaiss
    script: build-lib.sh   # [not win]
    script: build-lib.bat  # [win]
    script_interpreter: sh build-lib.sh {{ target }}  # [not win]
    build:
      string: "{{ target }}_h{{ PKG_HASH }}_{{ number }}"
      run_exports:
        - {{ pin_compatible('libfaiss', exact=True) }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - llvm-openmp   # [osx]
        - cmake >=3.17  # [win]
        - cmake-local   # [not win]
      host:
        - mkl >=2018
        - blas =*=mkl
        - cudatoolkit {{ cudatoolkit }}  # [cudatoolkit != "None"]
      run:
        - mkl >=2018
        - blas =*=mkl
        - {{ pin_compatible('cudatoolkit') }}  # [cudatoolkit != "None"]
    test:
      commands:
        - test -f $PREFIX/lib/libfaiss.so              # [linux]
        - test -f $PREFIX/lib/libfaiss.dylib           # [osx]
        - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
        - conda inspect objects -p $PREFIX $PKG_NAME   # [osx]

  - name: faiss
    script: build-pkg.sh   # [not win]
    script: build-pkg.bat  # [win]
    script_interpreter: sh build-pkg.sh {{ target }}  # [not win]
    build:
      string: "py{{ PY_VER }}_{{ target }}_h{{ PKG_HASH }}_{{ number }}"
    requirements:
      build:
        - {{ compiler('cxx') }}
        - swig
        - cmake >=3.17  # [win]
        - cmake-local   # [not win]
      host:
        - python {{ python }}
        - numpy 1.11.*
        - {{ pin_subpackage('libfaiss', exact=True) }}
      run:
        - python {{ python }}
        - {{ pin_compatible('numpy') }}
        - {{ pin_subpackage('libfaiss', exact=True) }}
    test:
      requires:
        - numpy
        - scipy
      commands:
        - python -m unittest discover tests/
      source_files:
        - tests/

  # NOTE: Available CMake version for linux/osx is currently too old.
  - name: cmake-local
    version: 3.17
    script: install-cmake.sh
    build:
      skip: True  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
