package:
  name: faiss-cpu
  version: "{{ FAISS_BUILD_VERSION }}"

source:
  git_url: ../

requirements:
  build:
    - {{ compiler('cxx') }}
    - llvm-openmp # [osx]
    - setuptools
    - swig

  host:
    - intel-openmp # [osx]
    - python {{ python }}
    - numpy 1.11.*
    - mkl

  run:
    - intel-openmp # [osx]
    - python {{ python }}
    - numpy >=1.11
    - mkl
    - blas=*=mkl

build:
  number: {{ FAISS_BUILD_NUMBER }}

test:
  imports:
    - faiss
  source_files: tests
  commands:
    - python -m unittest discover tests/

about:
  home: https://github.com/facebookresearch/faiss
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A library for efficient similarity search and clustering of dense vectors.
