version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  deploy_linux_gpu:
    parameters:
      label:
        type: string
        default: main
      cuda:
        type: string
      cuda_archs:
        type: string
    machine:
      resource_class: gpu.nvidia.medium
      image: ubuntu-1604-cuda-10.1:201909-23
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build packages
          command: |
            docker build -t faiss -f conda/Dockerfile.cuda<<parameters.cuda>> .
            docker run --gpus all \
              -e CUDA_ARCHS="<<parameters.cuda_archs>>" \
              faiss \
              conda build faiss-gpu --variants '{ "cudatoolkit": "<<parameters.cuda>>" }' \
                --user pytorch --label <<parameters.label>>
          no_output_timeout: 60m

workflows:
  version: 2
  build:
    jobs:
      - deploy_linux_gpu:
          name: Linux GPU packages (CUDA 11.2)
          cuda: "11.2"
          cuda_archs: "75"
