package:
  name: faiss-gpu
  version: "{{ FAISS_BUILD_VERSION }}"

source:
  git_url: ../

requirements:
  build:
    - {{ compiler('cxx') }}
    - llvm-openmp # [osx]
    - setuptools
    - swig

  host:
    - intel-openmp # [osx]
    - python {{ python }}
    - numpy 1.11.*
    - mkl
    - cudatoolkit {{ cudatoolkit }}

  run:
    - intel-openmp # [osx]
    - python {{ python }}
    - numpy >=1.11
    - mkl
    - blas=*=mkl
    - cudatoolkit {{ cudatoolkit }}

#test:
#  requires:
#    - {{ cuda_feature }}
#  imports:
#    - faiss
#  source_files: tests
#  commands:
#    - python -m unittest discover tests/ -v
#    - python -c 'import faiss; print(faiss.StandardGpuResources)'

about:
  home: https://github.com/facebookresearch/faiss
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A library for efficient similarity search and clustering of dense vectors.
