{% set cuda_feature = 'cuda' + CUDA_VERSION.replace('.', '') %}
package:
  name: faiss-gpu
  version: "{{ FAISS_BUILD_VERSION }}"

source:
  git_rev: packages2 # v{{ environ.get('FAISS_BUILD_VERSION') }}
  git_url: https://github.com/beauby/faiss.git # https://github.com/facebookresearch/faiss.git

requirements:
  build:
    - {{ compiler('cxx') }}
    - llvm-openmp # [osx]
    - setuptools
    - swig

  host:
    - intel-openmp # [osx]
    - python {{ python }}
    - numpy 1.11.*
    - mkl

  run:
    - intel-openmp # [osx]
    - python {{ python }}
    - numpy >=1.11
    - mkl
    - blas=*=mkl

build:
  number: {{ FAISS_BUILD_NUMBER }}
  string: py{{ py }}_cuda{{ CUDA_VERSION }}_{{ FAISS_BUILD_NUMBER }}
  features:
    - {{ cuda_feature }}

#test:
#  requires:
#    - {{ cuda_feature }}
#  imports:
#    - faiss
#  source_files: tests
#  commands:
#    - python -m unittest discover tests/ -v
#    - python -c 'import faiss; print(faiss.StandardGpuResources)'

about:
  home: https://github.com/facebookresearch/faiss
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A library for efficient similarity search and clustering of dense vectors.
