package:
  name: faiss-gpu
  version: "{{ FAISS_BUILD_VERSION }}"

source:
  git_url: ../../

requirements:
  build:
    - {{ compiler('cxx') }}
    - llvm-openmp # [osx]
    - setuptools
    - swig

  host:
    - python {{ python }}
    - intel-openmp # [osx]
    - numpy 1.11.*
    - mkl
    - cudatoolkit {{ cudatoolkit }}

  run:
    - python
    - {{ pin_compatible('intel-openmp') }} # [osx]
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('mkl') }}
    - cudatoolkit

build:
  number: {{ FAISS_BUILD_NUMBER }}

about:
  home: https://github.com/facebookresearch/faiss
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A library for efficient similarity search and clustering of dense vectors.
